### ISSUE TITLE
php71u-pecl-ssh2

### ISSUE THREAD

**Issue by cheese1** [iusrepo/wishlist#176]
### What new package do you want?

php71u-pecl-ssh2

### Why?
I am preparing a migration from php54 to php71 and our application needs pecl-ssh2.
The version 0.13 (the last stable one) would be sufficient for me.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by b-harper** [comment]
Hey @cheese1,

Thanks for this request.  Unfortunately, there is still not a stable release for PHP 7, as it requires 1.0+. The [README.md][0] has the following;

> The extension in the master branch is not in a state you should deploy on a production server.

We also have an open request for php70u-pecl-ssh2, see #88.  It would seem they are in no hurry and you might want to look at other options.

[0]: https://github.com/php/pecl-networking-ssh2/blob/aa1739ac26c2177d33ab8d064021032bdc2c3a40/README.md

**Comment by cheese1** [comment]
i have no README.md in version 0.13 (stable). is 0.13 not suitable for php71?

**Comment by b-harper** [comment]
Hey @cheese1,

From [ssh2's pecl page][0]:

>  ssh2 1.0 and above is PHP 7 only. To install a version that is PHP 5 compatible you can run 'pecl install ssh2-0.13'

[0]: https://pecl.php.net/package/ssh2

**Comment by tvlooy** [comment]
phpseclib seems a good alternative

**Comment by carlwgeorge** [comment]
PHP 7.1 is now EOL, so we won't be creating any more packages for it.

It looks three months ago upstream finally tagged a non-alpha [1.2 release](https://pecl.php.net/package/ssh2/1.2) (however still beta) that is compatible with PHP 7.  Because of that, I'm willing to attempt a package of this for PHP 7.2 (php72u-pecl-ssh2) or 7.3 (php73-pecl-ssh2).  If anyone would fine that useful, please open a new wishlist issue to request it.
