### ISSUE TITLE
python3-libselinux

### ISSUE THREAD

**Issue by rgarrigue** [iusrepo/wishlist#204]
### What new package do you want?

libselinux-python for python3, as in https://fedora.pkgs.org/rawhide/fedora-x86_64/python3-libselinux-2.8-2.fc29.x86_64.rpm.html

### Why?

Ansible requires python 3.5 or above to work. I'm using IUS repository to get python36. But it's missing those binding. I spent a bit of time looking for a workaround but it's strongly tied to selinux and python. I could work around that building the RPM from the SRPM & so on, but that would need some times and one more ugly hack in my builds... For now I'm disabling SELinux entirely for now, which requires a reboot.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

OK. Can share an example if needed.

**Comment by rgarrigue** [comment]
@carlwgeorge, sorry to bother you about this but do you have a rought idea if this will be done, if yes an approximative ETA ? Or maybe I can contribute this myself given the right contribute guidance ?

**Comment by carlwgeorge** [comment]
I have no idea when I'll get time to investigate this, and even then we don't do ETAs.

This won't be as simple as converting a Fedora spec file (our standard practice) because Fedora's `python3-libselinux` is built from the `libselinux` spec file.  You'll need to extract the `python3-libselinux` subpackage from [libselinux.spec](https://src.fedoraproject.org/rpms/libselinux/blob/master/f/libselinux.spec).  That includes deciphering the `%build` and `%install` sections to only run the necessary commands, which will involve getting your head wrapped around the [upstream Makefile](https://github.com/SELinuxProject/selinux/blob/master/Makefile).  Everything will need to be adapted to build against the stock `libselinux` instead of building against whatever the Makefile compiles.  That probably means that this hypothetical package will be forever tied to the same libselinux version as EL7.  Now that I think about that aspect, it's probably smarter to start with the [EL7 spec file](https://git.centos.org/blob/rpms!libselinux.git/c7/SPECS!libselinux.spec) instead of the Fedora one.

**Comment by sar009** [comment]
@carlwgeorge where you able to figure out this. Even I am having the same ansible problem but in my case i cant disable SELinux.

**Comment by carlwgeorge** [comment]
No, I haven't had time to look into this yet.

**Comment by carlwgeorge** [comment]
RHEL 7.7 beta has [added python3](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7-beta/html/7.7_release_notes/new_features#BZ-1597718).  Red Hat can now enable the python3 subpackage of the libselinux package.  They haven't yet, but I've [requested it](https://bugzilla.redhat.com/show_bug.cgi?id=1719978).  I'm optimistic that they will resolve that in the final 7.7 release.

**Comment by carlwgeorge** [comment]
Red Hat at least for now has declined to turn on the python3 subpackage in the libselinux spec file.

https://bugzilla.redhat.com/show_bug.cgi?id=1719978

I have attempted to to extract the python3 subpackage into it's own spec file. It seems to work as best I can tell.  I have submitted it for review as an EPEL7-only package.

https://bugzilla.redhat.com/show_bug.cgi?id=1754039

**Comment by carlwgeorge** [comment]
Red Hat has changed their mind and are now working on enabling libselinux-python3 from the main spec file like I originally requested.

> As we managed to get acknowledgements from PM, devel, and QE, we are initiating the process to include the libselinux-python3 subpackage into RHEL 7.

https://bugzilla.redhat.com/show_bug.cgi?id=1719978#c26
